name             'selinux'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Deprecated. Chef Infra Client 18+ includes built-in SELinux resources.'
version          '6.2.5'
source_url       'https://github.com/sous-chefs/selinux'
issues_url       'https://github.com/sous-chefs/selinux/issues'
chef_version     '>= 15.3'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'
