# frozen_string_literal: true

name             'selinux'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Manages SELinux policy state and rules.'
version          '6.2.5'
source_url       'https://github.com/sous-chefs/selinux'
issues_url       'https://github.com/sous-chefs/selinux/issues'
chef_version     '>= 15.3'

supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2.0'
supports 'centos_stream', '>= 9.0'
supports 'debian', '>= 12.0'
supports 'fedora'
supports 'oracle', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'ubuntu', '>= 22.04'
